import './bootstrap';
import '../css/app.css';
import '../scss/telegram.scss';

// Import dependencies
import { createApp, h } from 'vue';
import { createInertiaApp } from '@inertiajs/vue3';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import { ZiggyVue } from 'ziggy-js';
import { Ziggy } from './ziggy';

// Initialize Alpine.js
import Alpine from 'alpinejs';
window.Alpine = Alpine;
Alpine.start();

// Import custom scripts
import './case-form-xampp.js';

// Initialize Inertia only on pages that include the #app element generated by Inertia (e.g. Jetstream/Breeze views)
const inertiaRoot = document.getElementById('app');
if (inertiaRoot && inertiaRoot.dataset && inertiaRoot.dataset.page) {
    createInertiaApp({
        title: (title) => `${title} - ${import.meta.env.VITE_APP_NAME || 'Laravel'}`,
        resolve: (name) => resolvePageComponent(
            `./Pages/${name}.vue`,
            import.meta.glob('./Pages/**/*.vue')
        ),
        setup({ el, App, props, plugin }) {
            return createApp({ render: () => h(App, props) })
                .use(plugin)
                .use(ZiggyVue, Ziggy)
                .mount(el);
        },
        progress: {
            color: '#4B5563',
            showSpinner: true,
        },
    });
}

